"use client";

import React, { useState, useEffect } from 'react';
import ImageManager from './ImageManager';
import DynamicSelector from './DynamicSelector';
import { getNextSkuNumber } from '@/utils/supabase';


/**
 * Головна форма додавання/редагування товару
 * Модульна та зручна для телефону
 */
export default function ProductForm({
    product,
    onSave,
    onCancel,
    categories = [],
    existingBrands = [],
    existingModels = []
}) {
    const [formData, setFormData] = useState({
        name: '',
        price: '',
        quantity: 1, // Додаємо кількість
        sku: '', // Додаємо SKU
        oe_number: '',
        car_brand: '',
        compatible_models: [],
        category_id: '',
        condition: 'Б/У',
        description: '',
        status: 'draft', // По замовчуванню - чернетка (найкраще для телефону)
        main_image: '',
        images: [],
        ...product
    });

    const [nextNumber, setNextNumber] = useState(null);

    // --- ОБЧИСЛЕННЯ КАТЕГОРІЙ ---
    const selectedCatObj = categories.find(c => c.id == formData.category_id);
    const currentParentId = selectedCatObj?.parent_id || selectedCatObj?.id || '';
    const currentSubcatId = selectedCatObj?.parent_id ? selectedCatObj.id : '';

    const mainCategories = categories.filter(c => !c.parent_id);
    const availableSubcats = categories.filter(c => c.parent_id == currentParentId);

    // Блокуємо скрол фону при відкритій модалці
    useEffect(() => {
        document.body.style.overflow = 'hidden';

        // Отримуємо наступний номер для SKU тільки для нових товарів
        if (!product?.id) {
            getNextSkuNumber().then(num => setNextNumber(num));
        }

        return () => {
            document.body.style.overflow = 'unset';
        };
    }, [product?.id]);

    // Автоматична генерація SKU при зміні марки або отриманні номера
    useEffect(() => {
        if (!product?.id && nextNumber) {
            let prefix = 'AP'; // Default prefix
            if (formData.car_brand) {
                // Беремо перші 2 літери марки у верхньому регістрі
                prefix = formData.car_brand.substring(0, 2).toUpperCase();
            }

            // Оновлюємо SKU тільки якщо він порожній або вже має стандартний формат (Prefix + Number)
            const currentSku = formData.sku;
            const isAutoGenerated = !currentSku || /^[A-Z]{2}\d+$/.test(currentSku);

            if (isAutoGenerated) {
                setFormData(prev => ({ ...prev, sku: `${prefix}${nextNumber}` }));
            }
        }
    }, [formData.car_brand, nextNumber, product?.id]);

    const handleSubmit = (e) => {
        e.preventDefault();

        let dataToSave = { ...formData };

        // Якщо це чернетка, підставляємо тимчасові дані для порожніх обов'язкових полів
        if (dataToSave.status === 'draft') {
            if (!dataToSave.name) dataToSave.name = 'Нова запчастина (Фото з телефону)';
            if (!dataToSave.price) dataToSave.price = 0;
            // SKU вже генерується автоматично або вписаний вручну
        }

        // Запобігаємо помилці типу даних для category_id
        if (dataToSave.category_id === '') {
            dataToSave.category_id = null;
        }

        // Видаляємо об'єкт category (приєднана таблиця), оскільки такої колонки немає в products
        const { category, ...finalData } = dataToSave;

        onSave(finalData);
    };

    return (
        <div className="fixed inset-0 z-[100] bg-slate-900/60 lg:bg-transparent backdrop-blur-sm lg:backdrop-blur-none flex items-end justify-center lg:justify-end p-0">
            {/* Overlay for mobile/tablet only */}
            <div className="fixed inset-0 lg:hidden" onClick={onCancel} />

            {/* Form Container */}
            <div className="bg-white w-full lg:w-[600px] xl:w-[700px] rounded-t-[2.5rem] lg:rounded-none lg:rounded-l-[2rem] shadow-2xl flex flex-col h-[95vh] lg:h-screen animate-in slide-in-from-bottom lg:slide-in-from-right duration-300 relative z-10 border-l border-slate-100">

                {/* Шапка модалки */}
                <div className="p-6 border-b border-slate-100 flex items-center justify-between bg-white z-10 md:rounded-t-[2.5rem] shrink-0">
                    <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
                        <span className="w-1.5 h-6 bg-blue-600 rounded-full"></span>
                        {product?.id ? 'Редагувати запчастину' : 'Нова запчастина'}
                    </h2>
                    <button onClick={onCancel} className="text-slate-400 hover:text-slate-600 p-2 bg-slate-50 rounded-full transition-all">
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>

                <form
                    id="productForm"
                    onSubmit={handleSubmit}
                    noValidate={formData.status === 'draft'}
                    className="overflow-y-auto p-6 md:p-10 space-y-8 scrollbar-hide flex-grow pb-32"
                >

                    {/* СЕКЦІЯ 1: ФОТО (НАЙВАЖЛИВІШЕ) */}
                    <section className="space-y-4">
                        <ImageManager
                            images={formData.images}
                            mainImage={formData.main_image}
                            onChange={(images, main) => setFormData(prev => ({ ...prev, images, main_image: main }))}
                        />
                    </section>

                    {/* СЕКЦІЯ 2: ОСНОВНА ІНФО */}
                    <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        <div className="md:col-span-2 space-y-2">
                            <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider ml-1">Назва запчастини</label>
                            <input
                                type="text"
                                required={formData.status === 'active'}
                                placeholder="Приклад: Бампер передній"
                                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:border-blue-500 text-slate-900 font-medium placeholder:text-slate-500 outline-none"
                                value={formData.name}
                                onChange={e => setFormData(p => ({ ...p, name: e.target.value }))}
                            />
                        </div>
                        <div className="space-y-2">
                            <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider ml-1">Артикул (SKU)</label>
                            <input
                                type="text"
                                required={formData.status === 'active'}
                                placeholder="TR-12345"
                                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:border-blue-500 text-slate-900 font-bold placeholder:text-slate-500 outline-none"
                                value={formData.sku}
                                onChange={e => setFormData(p => ({ ...p, sku: e.target.value }))}
                            />
                        </div>
                        <div className="md:col-span-1 space-y-2">
                            <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider ml-1">Ціна (грн)</label>
                            <input
                                type="number"
                                required={formData.status === 'active'}
                                placeholder="0"
                                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:border-blue-500 text-blue-600 font-bold text-lg placeholder:text-slate-500 outline-none"
                                value={formData.price}
                                onChange={e => setFormData(p => ({ ...p, price: e.target.value }))}
                            />
                        </div>
                        <div className="md:col-span-1 space-y-2">
                            <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider ml-1">К-сть (шт)</label>
                            <input
                                type="number"
                                min="0"
                                required={formData.status === 'active'}
                                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:border-blue-500 text-slate-900 font-bold text-lg outline-none"
                                value={formData.quantity}
                                onChange={e => setFormData(p => ({ ...p, quantity: parseInt(e.target.value) || 0 }))}
                            />
                        </div>
                        <div className="md:col-span-1 space-y-2">
                            <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider ml-1">OE-номер</label>
                            <input
                                type="text"
                                placeholder="13117289"
                                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:border-blue-500 text-slate-900 font-medium placeholder:text-slate-500 outline-none"
                                value={formData.oe_number}
                                onChange={e => setFormData(p => ({ ...p, oe_number: e.target.value }))}
                            />
                        </div>
                    </section>

                    {/* СЕКЦІЯ 3: СУМІСНІСТЬ (ДИНАМІЧНА) */}
                    <section className="grid grid-cols-1 md:grid-cols-2 gap-6 bg-slate-50 p-6 rounded-3xl border border-slate-100">
                        <DynamicSelector
                            label="Марка автомобіля"
                            options={existingBrands}
                            value={formData.car_brand}
                            onChange={val => setFormData(p => ({ ...p, car_brand: val }))}
                        />
                        <DynamicSelector
                            label="Сумісні моделі"
                            options={existingModels.filter(m => !formData.car_brand || existingModels.includes(m))} // Тут можна додати фільтр за маркою, якщо є словник
                            value={formData.compatible_models}
                            onChange={val => setFormData(p => ({ ...p, compatible_models: val }))}
                            multiple={true}
                        />
                    </section>

                    {/* СЕКЦІЯ 4: КАТЕГОРІЯ ТА ПІДКАГЕТОРІЯ */}
                    <section className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="space-y-2">
                            <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider ml-1">Головна категорія</label>
                            <select
                                required={formData.status === 'active'}
                                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:border-blue-500 text-slate-900 font-medium outline-none"
                                value={currentParentId}
                                onChange={e => {
                                    const newParentId = e.target.value;
                                    // При зміні головної категорії скидаємо підкатегорію і зберігаємо ID головної
                                    setFormData(p => ({ ...p, category_id: newParentId }));
                                }}
                            >
                                <option value="">Виберіть категорію</option>
                                {mainCategories.map(cat => (
                                    <option key={cat.id} value={cat.id}>{cat.name}</option>
                                ))}
                            </select>
                        </div>
                        <div className="space-y-2">
                            <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider ml-1">Підкатегорія</label>
                            <select
                                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:border-blue-500 text-slate-900 font-medium outline-none disabled:opacity-50"
                                value={currentSubcatId}
                                disabled={!currentParentId}
                                onChange={e => {
                                    const newSubcatId = e.target.value;
                                    // Зберігаємо ID підкатегорії (або головної, якщо підкатегорію скинуто)
                                    setFormData(p => ({ ...p, category_id: newSubcatId || currentParentId }));
                                }}
                            >
                                <option value="">{currentParentId && availableSubcats.length > 0 ? 'Виберіть підкатегорію' : 'Немає підкатегорій'}</option>
                                {availableSubcats.map(cat => (
                                    <option key={cat.id} value={cat.id}>{cat.name}</option>
                                ))}
                            </select>
                        </div>
                    </section>

                    {/* СЕКЦІЯ 5: ОПИС І СТАН */}
                    <section className="space-y-6">
                        <div className="flex gap-4">
                            {['Б/У', 'Новий'].map(c => (
                                <button
                                    key={c}
                                    type="button"
                                    onClick={() => setFormData(p => ({ ...p, condition: c }))}
                                    className={`flex-1 py-3 rounded-xl font-bold text-sm transition-all ${formData.condition === c ? 'bg-slate-900 text-white shadow-lg' : 'bg-slate-50 text-slate-500 border border-slate-200'}`}
                                >
                                    {c}
                                </button>
                            ))}
                        </div>

                        <div className="space-y-2">
                            <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider ml-1">Опис (необов'язково)</label>
                            <textarea
                                rows="4"
                                placeholder="Додаткова інформація про деталь..."
                                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:border-blue-500 text-slate-900 font-medium placeholder:text-slate-500 outline-none resize-none"
                                value={formData.description}
                                onChange={e => setFormData(p => ({ ...p, description: e.target.value }))}
                            />
                        </div>
                    </section>

                    {/* КРАЙНЯ СЕКЦІЯ: ТИП (АКТИВНИЙ / ЧЕРНЕТКА) */}
                    <section className="flex items-center justify-between p-4 bg-blue-50 rounded-2xl border border-blue-100">
                        <span className="text-xs font-bold text-blue-900 uppercase tracking-widest leading-none">Опублікувати відразу?</span>
                        <button
                            type="button"
                            onClick={() => setFormData(p => ({ ...p, status: p.status === 'active' ? 'draft' : 'active' }))}
                            className={`w-14 h-8 rounded-full relative transition-all ${formData.status === 'active' ? 'bg-blue-600' : 'bg-slate-300'}`}
                        >
                            <div className={`absolute top-1 w-6 h-6 bg-white rounded-full transition-all ${formData.status === 'active' ? 'left-7' : 'left-1'}`} />
                        </button>
                    </section>

                </form>

                {/* КНОПКИ ДІЇ - FIXED BOTTOM */}
                <div className="p-6 bg-white/80 backdrop-blur-md border-t border-slate-100 flex gap-3 shrink-0">
                    <button
                        type="button"
                        onClick={onCancel}
                        className="flex-1 py-4 border border-slate-200 rounded-2xl font-bold uppercase text-[10px] tracking-widest text-slate-500 hover:bg-slate-50 transition-all"
                    >
                        Скасувати
                    </button>
                    <button
                        form="productForm"
                        type="submit"
                        className="flex-[2] py-4 bg-blue-600 text-white rounded-2xl font-bold uppercase text-[10px] tracking-[0.2em] shadow-xl shadow-blue-200 hover:bg-blue-700 transition-all active:scale-95"
                    >
                        Зберегти запчастину
                    </button>
                </div>
            </div>
        </div>
    );
}
